service: seek-lunch-train
frameworkVersion: "3.23.0"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:ap-southeast-2:*:table/seek-lunch-train"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:ap-southeast-2:*:table/seek-lunch-train/index/*"
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  slack:
    handler: src/app.handler
    name: seek-lunch-train
    events:
      - http:
          path: /
          method: post
  processor:
    handler: src/processor.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - seekLunchTrainQueue
              - Arn

resources:
  Resources:
    seekLunchTrain:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: seek-lunch-train
        AttributeDefinitions:
          - AttributeName: creatorId
            AttributeType: S
          - AttributeName: trainId
            AttributeType: S
        KeySchema:
          - AttributeName: creatorId
            KeyType: HASH
          - AttributeName: trainId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TimeToLiveSpecification:
          Enabled: true
          AttributeName: ttl

    seekLunchTrainQueue:
      Type: "AWS::SQS::Queue"
      # TODO investigate FIFO queue
plugins:
  - serverless-esbuild
  - serverless-offline
